[2024-10-25T16:35:52.975+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: temp_data_pipeline_dag.scrape_task scheduled__2024-10-24T00:00:00+00:00 [queued]>
[2024-10-25T16:35:52.980+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: temp_data_pipeline_dag.scrape_task scheduled__2024-10-24T00:00:00+00:00 [queued]>
[2024-10-25T16:35:52.980+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-25T16:35:52.980+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-10-25T16:35:52.980+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-25T16:35:52.987+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_task> on 2024-10-24 00:00:00+00:00
[2024-10-25T16:35:52.990+0000] {standard_task_runner.py:55} INFO - Started process 564 to run task
[2024-10-25T16:35:52.993+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'temp_data_pipeline_dag', 'scrape_task', 'scheduled__2024-10-24T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/temp-***.py', '--cfg-path', '/tmp/tmpcm1s25cw']
[2024-10-25T16:35:52.994+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask scrape_task
[2024-10-25T16:35:53.031+0000] {task_command.py:388} INFO - Running <TaskInstance: temp_data_pipeline_dag.scrape_task scheduled__2024-10-24T00:00:00+00:00 [running]> on host 97df66c4b684
[2024-10-25T16:35:53.065+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=santosh
AIRFLOW_CTX_DAG_ID=temp_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=scrape_task
AIRFLOW_CTX_EXECUTION_DATE=2024-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-24T00:00:00+00:00
[2024-10-25T16:35:53.065+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: scrape_and_save() missing 1 required positional argument: 'urls'
[2024-10-25T16:35:53.069+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=temp_data_pipeline_dag, task_id=scrape_task, execution_date=20241024T000000, start_date=20241025T163552, end_date=20241025T163553
[2024-10-25T16:35:53.073+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task scrape_task (scrape_and_save() missing 1 required positional argument: 'urls'; 564)
[2024-10-25T16:35:53.091+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-25T16:35:53.106+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
